"""empty message

Revision ID: 428bd91acead
Revises: 
Create Date: 2021-05-12 15:01:18.440814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '428bd91acead'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id_number', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email')
    )
    op.create_table('mybooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('authors', sa.String(length=200), nullable=False),
    sa.Column('publisher', sa.String(length=100), nullable=False),
    sa.Column('publishedDate', sa.String(length=50), nullable=False),
    sa.Column('pageCount', sa.String(length=50), nullable=False),
    sa.Column('isbn', sa.String(length=200), nullable=False),
    sa.Column('categories', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('fechacompra', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mybooks')
    op.drop_table('user')
    # ### end Alembic commands ###
