"""empty message

<<<<<<< HEAD:migrations/versions/c933e9126248_.py
Revision ID: c933e9126248
Revises: 
Create Date: 2021-05-01 00:03:44.803938
=======
Revision ID: 731d22ae8b6e
Revises: 
Create Date: 2021-05-04 04:26:10.414200
>>>>>>> 54dfdf6a5edb16b1252f6dc25f9544aa8610ef01:migrations/versions/731d22ae8b6e_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:migrations/versions/c933e9126248_.py
revision = 'c933e9126248'
=======
revision = '731d22ae8b6e'
>>>>>>> 54dfdf6a5edb16b1252f6dc25f9544aa8610ef01:migrations/versions/731d22ae8b6e_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id_number', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('my_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('authors', sa.String(length=200), nullable=False),
    sa.Column('publisher', sa.String(length=100), nullable=False),
    sa.Column('publishedDate', sa.String(length=16), nullable=False),
    sa.Column('pageCount', sa.String(length=10), nullable=False),
    sa.Column('printType', sa.String(length=20), nullable=False),
    sa.Column('categories', sa.String(length=100), nullable=False),
    sa.Column('averageRating', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('smallThumbnail', sa.String(length=200), nullable=False),
    sa.Column('thumbnail', sa.String(length=200), nullable=False),
    sa.Column('textSnippet', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessionID',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_token', sa.String(length=150), nullable=True),
    sa.Column('duedate', sa.String(length=18), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessionID')
    op.drop_table('my_books')
    op.drop_table('user')
    # ### end Alembic commands ###
